package wom.controller.command.bootstrap
{
   import peak.messaging.IncomingMessageMap;
   import wom.controller.PCommand;
   import wom.controller.command.HandleAllianceChatMessageReceivedEventNotificationCommand;
   import wom.controller.command.HandleAuthResponseCommand;
   import wom.controller.command.HandleBattlePointsChangedEventNotificationCommand;
   import wom.controller.command.HandleDefaultResponseCommand;
   import wom.controller.command.HandleEventPointsChangedEventNotificationCommand;
   import wom.controller.command.HandleMaintenanceNotificationCommand;
   import wom.controller.command.HandleRaceStatusChangedEventNotificationCommand;
   import wom.controller.command.HandleStatusNotificationCommand;
   import wom.controller.command.alliance.HandleAllianceStatusChangedNotificationCommand;
   import wom.controller.command.alliance.HandleAllianceUnitsReceivedEventNotificationCommand;
   import wom.controller.command.alliance.HandleCancelAllianceInvitationResponseCommand;
   import wom.controller.command.alliance.HandleCreateAllianceResponseCommand;
   import wom.controller.command.alliance.HandleEditAllianceResponseCommand;
   import wom.controller.command.alliance.HandleGetAllianceCandidatesResponseCommand;
   import wom.controller.command.alliance.HandleGetAllianceInfoResponseCommand;
   import wom.controller.command.alliance.HandleGetAllianceMemberContributionsResponseCommand;
   import wom.controller.command.alliance.HandleGetAllianceMembersResponseCommand;
   import wom.controller.command.alliance.HandleGetAlliancesPageResponseCommand;
   import wom.controller.command.alliance.HandleGetRequestedAlliancesResponseCommand;
   import wom.controller.command.alliance.HandleGetTournamentsPageResponseCommand;
   import wom.controller.command.alliance.HandleGetUnitsOfAllianceMemberResponseCommand;
   import wom.controller.command.alliance.HandleInviteToAllianceResponseCommand;
   import wom.controller.command.alliance.HandleJoinAllianceResponseCommand;
   import wom.controller.command.alliance.HandleKickAllianceMemberResponseCommand;
   import wom.controller.command.alliance.HandleQuitAllianceResponseCommand;
   import wom.controller.command.alliance.HandleRemoveRejectedAllianceInvitationResponseCommand;
   import wom.controller.command.alliance.HandleReplyToAllianceInvitationNotificationCommand;
   import wom.controller.command.alliance.HandleReplyToAllianceInvitationResponseCommand;
   import wom.controller.command.alliance.HandleReplyToJoinAllianceRequestResponseCommand;
   import wom.controller.command.alliance.HandleSearchAllianceCandidateResponseCommand;
   import wom.controller.command.alliance.HandleSearchAllianceResponseCommand;
   import wom.controller.command.alliance.HandleTransferUnitsToAllianceMemberResponseCommand;
   import wom.controller.command.alliance.HandleUserIsInvitedToAllianceNotificationCommand;
   import wom.controller.command.beast.HandleBeastStatusChangedEventNotificationCommand;
   import wom.controller.command.beast.HandleBeastUnlockedEventNotificationCommand;
   import wom.controller.command.beast.HandleCaptureBeastResponseCommand;
   import wom.controller.command.beast.HandleEvolveBeastResponseCommand;
   import wom.controller.command.beast.HandleFreezeBeastResponseCommand;
   import wom.controller.command.beast.HandleHealBeastResponseCommand;
   import wom.controller.command.beast.HandleThawBeastResponseCommand;
   import wom.controller.command.beast.HandleTrainBeastResponseCommand;
   import wom.controller.command.beast.HandleUnitsKilledForBeastEventNotificationCommand;
   import wom.controller.command.chat.HandleChatAuthResponseCommand;
   import wom.controller.command.chat.HandleUserBannedEventNotificationCommand;
   import wom.controller.command.city.HandleActivateBuildingResponseCommand;
   import wom.controller.command.city.HandleAllBuildingsRepairedEventNotificationCommand;
   import wom.controller.command.city.HandleApplyCityPlanResponseCommand;
   import wom.controller.command.city.HandleBankAllResourcesResponseCommand;
   import wom.controller.command.city.HandleBankGoldResponseCommand;
   import wom.controller.command.city.HandleBankResourcesResponseCommand;
   import wom.controller.command.city.HandleBeastCannonAmmoAmountChangedEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingActivatedEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingConstructionCancelledEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingDamagedEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingFortificationJobFinishedEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingFortificationJobScheduledEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingHelpedNotificationCommand;
   import wom.controller.command.city.HandleBuildingLevelUpgradeJobFinishedEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingLevelUpgradeJobScheduledEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingRecycledEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingRepairJobFinishedEventNotificationCommand;
   import wom.controller.command.city.HandleBuildingRepairJobScheduledEventNotificationCommand;
   import wom.controller.command.city.HandleBuyDecorationResponseCommand;
   import wom.controller.command.city.HandleCancelConstructionResponseCommand;
   import wom.controller.command.city.HandleCityBuildingMovedEventNotification;
   import wom.controller.command.city.HandleCityDimensionsUpdatedEventNotification;
   import wom.controller.command.city.HandleConstructBuildingResponseCommand;
   import wom.controller.command.city.HandleFortifyBuildingResponseCommand;
   import wom.controller.command.city.HandleGetCityPlansResponseCommand;
   import wom.controller.command.city.HandleGetWatchPostUnitsOfFriendResponseCommand;
   import wom.controller.command.city.HandleGoldBankedEventNotificationCommand;
   import wom.controller.command.city.HandleGoldTimerUpdatedEventNotificationCommand;
   import wom.controller.command.city.HandleInventoryUpdatedEventNotificationCommand;
   import wom.controller.command.city.HandleLoadCityPlanResponseCommand;
   import wom.controller.command.city.HandleMoveBuildingResponseCommand;
   import wom.controller.command.city.HandleNumberOfWorkersChangedEventNotificationCommand;
   import wom.controller.command.city.HandleRearmTrapsResponseCommand;
   import wom.controller.command.city.HandleRechargeCatapultResponseCommand;
   import wom.controller.command.city.HandleRecycleBuildingResponseCommand;
   import wom.controller.command.city.HandleResourceCapacityUpdatedEventNotificationCommand;
   import wom.controller.command.city.HandleResourcesChangedEventNotificationCommand;
   import wom.controller.command.city.HandleResourcesHarvestedEventNotificationCommand;
   import wom.controller.command.city.HandleSaveCityPlanResponseCommand;
   import wom.controller.command.city.HandleSetCityPlanSlotsResponseCommand;
   import wom.controller.command.city.HandleStartRepairsResponseCommand;
   import wom.controller.command.city.HandleTournamentAttackRemainingDurChangedEventNotificationCommand;
   import wom.controller.command.city.HandleTournamentEndedEventNotificationCommand;
   import wom.controller.command.city.HandleTournamentStatusChangedEventNotificationCommand;
   import wom.controller.command.city.HandleTransferWatchPostUnitsToFriendResponseCommand;
   import wom.controller.command.city.HandleUpgradeBuildingResponseCommand;
   import wom.controller.command.city.HandleUserStatusResponseCommand;
   import wom.controller.command.city.HandleWorldChatMessageReceivedEventNotificationCommand;
   import wom.controller.command.city.friendwatchpost.HandleFriendWatchpostHelpNotificationCommand;
   import wom.controller.command.combat.HandleEndAttackResponseCommand;
   import wom.controller.command.combat.HandleExtendAttackResponseCommand;
   import wom.controller.command.combat.HandleSkipNPCAttackResponseCommand;
   import wom.controller.command.combat.HandleStartAttackResponseCommand;
   import wom.controller.command.defense.HandleDelayNPCAttackResponseCommand;
   import wom.controller.command.defense.HandleNPCAttackTimeUpdatedEventNotificationCommand;
   import wom.controller.command.defense.HandlePrepareNPCAttackResponseCommand;
   import wom.controller.command.defense.HandleStartNPCAttackResponseCommand;
   import wom.controller.command.guest.HandleSetAvatarResponseCommand;
   import wom.controller.command.league.HandleGetLeagueMembersResponseCommand;
   import wom.controller.command.league.HandleSeasonEndedNotificationCommand;
   import wom.controller.command.league.HandleUserIsPlacedIntoALeagueNotificationCommand;
   import wom.controller.command.league.HandleUserIsRemovedFromLeagueNotificationCommand;
   import wom.controller.command.map.HandleGetMapInfoResponseCommand;
   import wom.controller.command.quest.HandleClaimQuestResponseCommand;
   import wom.controller.command.quest.HandleVisibleQuestsChangedNotificationCommand;
   import wom.controller.command.rank.HandleGetRankingPageResponseCommand;
   import wom.controller.command.report.HandleGetAttackLogsResponseCommand;
   import wom.controller.command.report.HandleGetBattleReportResponseCommand;
   import wom.controller.command.report.HandleReadAttackLogResponseCommand;
   import wom.controller.command.staff.HandleBuildingStaffAssignedEventNotificationCommand;
   import wom.controller.command.staff.HandleHireStaffResponseCommand;
   import wom.controller.command.staff.HandleWorkerStaffAssignedEventNotificationCommand;
   import wom.controller.command.store.HandleBuyItemResponseCommand;
   import wom.controller.command.store.HandleUnlockEventItemResponseCommand;
   import wom.controller.command.store.HandleUseEventItemReponseCommand;
   import wom.controller.command.tavern.HandleTavernSpinResponseCommand;
   import wom.controller.command.tuskhorn.HandleStartTuskHornAttackResponseCommand;
   import wom.controller.command.tutorial.HandleUpdateUserTutorialResponseCommand;
   import wom.controller.command.ui.HandleConfirmCaptchaResponseCommand;
   import wom.controller.command.ui.HandleShowCaptchaEventNotificationCommand;
   import wom.controller.command.unit.HandleEventItemQueueChangedEventNotificationCommand;
   import wom.controller.command.unit.HandleGetHiringStatusResponseCommand;
   import wom.controller.command.unit.HandleHireUnitResponseCommand;
   import wom.controller.command.unit.HandleHiringInfoChangedEventNotificationCommand;
   import wom.controller.command.unit.HandleQueuedHiringsCancelledEventNotificationCommand;
   import wom.controller.command.unit.HandleRecruitUnitJobScheduledEventNotificationCommand;
   import wom.controller.command.unit.HandleRecruitUnitResponseCommand;
   import wom.controller.command.unit.HandleRecruitmentCancelledEventNotificationCommand;
   import wom.controller.command.unit.HandleTrainUnitJobScheduledEventNotificationCommand;
   import wom.controller.command.unit.HandleTrainUnitResponseCommand;
   import wom.controller.command.unit.HandleUnitHiredEventNotificationCommand;
   import wom.controller.command.unit.HandleUnitLevelIncreasedEventNotificationCommand;
   import wom.controller.command.unit.HandleUnitRecruitedEventNotificationCommand;
   import wom.controller.command.unit.HandleUnitRewardsAddedEventNotificationCommand;
   import wom.controller.command.unit.HandleUnitTrainingCancelledEventNotificationCommand;
   import wom.controller.command.unit.HandleUnitsDeployedToWatchPostEventNotificationCommand;
   import wom.controller.command.unit.HandleUnitsExecutedEventNotificationCommand;
   import wom.controller.command.unit.HandleUnitsKilledInWatchPostEventNotificationCommand;
   import wom.controller.command.user.HandleExperiencePointsChangedEventNotificationCommand;
   import wom.controller.command.user.HandleGetUserIdsOfFriendsRespCommand;
   import wom.controller.command.user.HandleGoldAmountChangedEventNotificationCommand;
   import wom.controller.command.user.HandleGoldGiftReceivedEventNotificationCommand;
   import wom.controller.command.user.HandleItemInventoryChangedEventNotification;
   import wom.controller.command.user.HandleReconPointsChangedEventNotificationCommand;
   import wom.controller.command.user.HandleServerSpeedChangedEventNotificationCommand;
   import wom.controller.command.user.HandleSessionClosedNotificationCommand;
   import wom.controller.command.user.HandleSubscribedActionsUpdatedEventNotificationCommand;
   import wom.controller.command.user.HandleUpdatePigeonPostSubscriptionsMessageResponseCommand;
   import wom.controller.command.visit.HandleCityHelpedEventNotificationCommand;
   import wom.controller.command.visit.HandleDailyPerUserHelpCapacityReachedEventNotificationCommand;
   import wom.controller.command.visit.HandleHelpFriendResponseCommand;
   import wom.controller.command.visit.HandleSpyTimeoutEventNotificationCommand;
   import wom.controller.command.visit.HandleStartSpyingResponseCommand;
   import wom.controller.command.visit.HandleStartVisitingCityResponseCommand;
   import wom.controller.command.visit.HandleVisitCityEndedEventNotificationCommand;
   import wom.controller.event.MessageReceivedEvent;
   import wom.model.message.notification.AllBuildingsRepairedEventNotification;
   import wom.model.message.notification.AllianceChatMessageReceivedEventNotification;
   import wom.model.message.notification.BattlePointsChangedEventNotification;
   import wom.model.message.notification.BeastCannonAmmoAmountChanedEventNotification;
   import wom.model.message.notification.BeastStatusChangedEventNotification;
   import wom.model.message.notification.BeastUnlockedEventNotification;
   import wom.model.message.notification.BuildingActivatedEventNotification;
   import wom.model.message.notification.BuildingConstructionCancelledEventNotification;
   import wom.model.message.notification.BuildingDamagedEventNotification;
   import wom.model.message.notification.BuildingFortificationJobFinishedEventNotification;
   import wom.model.message.notification.BuildingFortificationJobScheduledNotification;
   import wom.model.message.notification.BuildingHelpedNotification;
   import wom.model.message.notification.BuildingLevelUpgradeJobFinishedEventNotification;
   import wom.model.message.notification.BuildingLevelUpgradeJobScheduledEventNotification;
   import wom.model.message.notification.BuildingRecycledEventNotification;
   import wom.model.message.notification.BuildingRepairJobFinishedEventNotification;
   import wom.model.message.notification.BuildingRepairJobScheduledEventNotification;
   import wom.model.message.notification.BuildingStaffAssignedEventNotification;
   import wom.model.message.notification.CityBuildingMovedEventNotification;
   import wom.model.message.notification.CityDimensionsUpdatedEventNotification;
   import wom.model.message.notification.CityHelpedEventNotification;
   import wom.model.message.notification.DailyPerUserHelpCapacityReachedEventNotification;
   import wom.model.message.notification.EventItemQueueChangedEventNotification;
   import wom.model.message.notification.EventPointsChangedEventNotification;
   import wom.model.message.notification.ExperiencePointsChangedEventNotification;
   import wom.model.message.notification.FriendWatchpostHelpNotification;
   import wom.model.message.notification.GetHiringStatusResponse;
   import wom.model.message.notification.GoldAmountChangedEventNotification;
   import wom.model.message.notification.GoldBankedEventNotification;
   import wom.model.message.notification.GoldGiftReceivedEventNotification;
   import wom.model.message.notification.GoldTimerUpdatedEventNotification;
   import wom.model.message.notification.HiringInfoChangedEventNotification;
   import wom.model.message.notification.InventoryUpdatedEventNotification;
   import wom.model.message.notification.ItemInventoryChangedEventNotification;
   import wom.model.message.notification.MaintenanceNotification;
   import wom.model.message.notification.NPCAttackTimeUpdatedEventNotification;
   import wom.model.message.notification.NumberOfWorkersChangedEventNotification;
   import wom.model.message.notification.QueuedHiringsCancelledEventNotification;
   import wom.model.message.notification.RaceStatusChangedEventNotification;
   import wom.model.message.notification.ReconPointsChangedEventNotification;
   import wom.model.message.notification.RecruitUnitJobScheduledEventNotification;
   import wom.model.message.notification.RecruitmentCancelledEventNotification;
   import wom.model.message.notification.ResourceCapacityUpdatedEventNotification;
   import wom.model.message.notification.ResourcesChangedEventNotification;
   import wom.model.message.notification.ResourcesHarvestedEventNotification;
   import wom.model.message.notification.ServerSpeedChangedEventNotification;
   import wom.model.message.notification.SessionClosedNotification;
   import wom.model.message.notification.ShowCaptchaEventNotification;
   import wom.model.message.notification.SpyTimeoutEventNotification;
   import wom.model.message.notification.StatusNotification;
   import wom.model.message.notification.SubscribedActionsUpdatedEventNotification;
   import wom.model.message.notification.TournamentAttackRemainingDurChangedEventNotification;
   import wom.model.message.notification.TournamentEndedEventNotification;
   import wom.model.message.notification.TournamentStatusChangedEventNotification;
   import wom.model.message.notification.TrainUnitJobScheduledEventNotification;
   import wom.model.message.notification.UnitHiredEventNotification;
   import wom.model.message.notification.UnitLevelIncreasedEventNotification;
   import wom.model.message.notification.UnitRecruitedEventNotification;
   import wom.model.message.notification.UnitRewardsAddedEventNotification;
   import wom.model.message.notification.UnitTrainingCancelledEventNotification;
   import wom.model.message.notification.UnitsDeployedToWatchPostEventNotification;
   import wom.model.message.notification.UnitsExecutedEventNotification;
   import wom.model.message.notification.UnitsKilledForBeastEventNotification;
   import wom.model.message.notification.UnitsKilledInWatchPostEventNotification;
   import wom.model.message.notification.UserBannedEventNotification;
   import wom.model.message.notification.VisibleQuestsChangedNotification;
   import wom.model.message.notification.VisitCityEndedEventNotification;
   import wom.model.message.notification.WorkerStaffAssignedEventNotification;
   import wom.model.message.notification.WorldChatMessageReceivedEventNotification;
   import wom.model.message.notification.alliance.AllianceStatusChangedNotification;
   import wom.model.message.notification.alliance.AllianceUnitsReceivedEventNotification;
   import wom.model.message.notification.alliance.ReplyToAllianceInvitationNotification;
   import wom.model.message.notification.alliance.UserIsInvitedToAllianceNotification;
   import wom.model.message.notification.league.SeasonEndedNotification;
   import wom.model.message.notification.league.UserIsPlacedIntoALeagueNotification;
   import wom.model.message.notification.league.UserIsRemovedFromLeagueNotification;
   import wom.model.message.response.ActivateBuildingResponse;
   import wom.model.message.response.ApplyCityPlanResponse;
   import wom.model.message.response.AuthResponse;
   import wom.model.message.response.BankAllResourcesResponse;
   import wom.model.message.response.BankGoldResponse;
   import wom.model.message.response.BankResourcesResponse;
   import wom.model.message.response.BuyDecorationResponse;
   import wom.model.message.response.BuyItemResponse;
   import wom.model.message.response.CancelConstructionResponse;
   import wom.model.message.response.CaptureBeastResponse;
   import wom.model.message.response.ChatAuthResponse;
   import wom.model.message.response.ClaimQuestResponse;
   import wom.model.message.response.ConfirmCaptchaResponse;
   import wom.model.message.response.ConstructBuildingResponse;
   import wom.model.message.response.DefaultResponse;
   import wom.model.message.response.DelayNPCAttackResponse;
   import wom.model.message.response.EndAttackResponse;
   import wom.model.message.response.EvolveBeastResponse;
   import wom.model.message.response.ExtendBattleDurationResponse;
   import wom.model.message.response.FortifyBuildingResponse;
   import wom.model.message.response.FreezeBeastResponse;
   import wom.model.message.response.GetAttackLogsResponse;
   import wom.model.message.response.GetBattleReportResponse;
   import wom.model.message.response.GetCityPlansResponse;
   import wom.model.message.response.GetMapInfoResponse;
   import wom.model.message.response.GetRankingPageResponse;
   import wom.model.message.response.GetUserIdsOfFriendsResp;
   import wom.model.message.response.GetWatchPostUnitsOfFriendResponse;
   import wom.model.message.response.HealBeastResponse;
   import wom.model.message.response.HelpFriendResponse;
   import wom.model.message.response.HireStaffResponse;
   import wom.model.message.response.HireUnitResponse;
   import wom.model.message.response.LoadCityPlanResponse;
   import wom.model.message.response.MoveBuildingResponse;
   import wom.model.message.response.PrepareNPCAttackResponse;
   import wom.model.message.response.ReadAttackLogResponse;
   import wom.model.message.response.RearmTrapsResponse;
   import wom.model.message.response.RechargeCatapultResponse;
   import wom.model.message.response.RecruitUnitResponse;
   import wom.model.message.response.RecycleBuildingResponse;
   import wom.model.message.response.SaveCityPlanResponse;
   import wom.model.message.response.SetCityPlanSlotsResponse;
   import wom.model.message.response.SkipNPCAttackResponse;
   import wom.model.message.response.StartAttackResponse;
   import wom.model.message.response.StartNPCAttackResponse;
   import wom.model.message.response.StartRepairsResponse;
   import wom.model.message.response.StartSpyingResponse;
   import wom.model.message.response.StartTuskHornAttackResponse;
   import wom.model.message.response.StartVisitingCityResponse;
   import wom.model.message.response.ThawBeastResponse;
   import wom.model.message.response.TrainBeastResponse;
   import wom.model.message.response.TrainUnitResponse;
   import wom.model.message.response.TransferWatchPostUnitsToFriendResponse;
   import wom.model.message.response.UnlockEventItemResponse;
   import wom.model.message.response.UpdatePigeonPostSubscriptionsMessageResponse;
   import wom.model.message.response.UpdateUserTutorialResponse;
   import wom.model.message.response.UpgradeBuildingResponse;
   import wom.model.message.response.UseEventItemResponse;
   import wom.model.message.response.UserStatusResponse;
   import wom.model.message.response.alliance.CancelAllianceInvitationResponse;
   import wom.model.message.response.alliance.CreateAllianceResponse;
   import wom.model.message.response.alliance.EditAllianceResponse;
   import wom.model.message.response.alliance.GetAllianceCandidatesResponse;
   import wom.model.message.response.alliance.GetAllianceInfoResponse;
   import wom.model.message.response.alliance.GetAllianceMemberContributionsResponse;
   import wom.model.message.response.alliance.GetAllianceMembersResponse;
   import wom.model.message.response.alliance.GetAlliancesPageResponse;
   import wom.model.message.response.alliance.GetRequestedAlliancesResponse;
   import wom.model.message.response.alliance.GetTournamentsPageResponse;
   import wom.model.message.response.alliance.GetUnitsOfAllianceMemberResponse;
   import wom.model.message.response.alliance.InviteToAllianceResponse;
   import wom.model.message.response.alliance.JoinAllianceResponse;
   import wom.model.message.response.alliance.KickAllianceMemberResponse;
   import wom.model.message.response.alliance.QuitAllianceResponse;
   import wom.model.message.response.alliance.RemoveRejectedAllianceInvitationResponse;
   import wom.model.message.response.alliance.ReplyToAllianceInvitationResponse;
   import wom.model.message.response.alliance.ReplyToJoinAllianceRequestResponse;
   import wom.model.message.response.alliance.SearchAllianceCandidateResponse;
   import wom.model.message.response.alliance.SearchAllianceResponse;
   import wom.model.message.response.alliance.TransferUnitsToAllianceMemberResponse;
   import wom.model.message.response.guest.SetAvatarResponse;
   import wom.model.message.response.league.GetLeagueMembersResponse;
   import wom.model.message.response.tavern.TavernSpinResponse;
   
   public class BootstrapMessageCommandMapCommand extends PCommand
   {
      
      public function BootstrapMessageCommandMapCommand()
      {
         super();
      }
      
      override public function execute() : void
      {
         var _loc1_:IncomingMessageMap = injector.getInstance(IncomingMessageMap);
         commandMap.mapEvent(_loc1_.getEventTypeFor(DefaultResponse),HandleDefaultResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(AuthResponse),HandleAuthResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ChatAuthResponse),HandleChatAuthResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(StatusNotification),HandleStatusNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(StartVisitingCityResponse),HandleStartVisitingCityResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(StartAttackResponse),HandleStartAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ConstructBuildingResponse),HandleConstructBuildingResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BankAllResourcesResponse),HandleBankAllResourcesResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BankResourcesResponse),HandleBankResourcesResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ResourcesChangedEventNotification),HandleResourcesChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ResourceCapacityUpdatedEventNotification),HandleResourceCapacityUpdatedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GoldAmountChangedEventNotification),HandleGoldAmountChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ExperiencePointsChangedEventNotification),HandleExperiencePointsChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ReconPointsChangedEventNotification),HandleReconPointsChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(EventPointsChangedEventNotification),HandleEventPointsChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BattlePointsChangedEventNotification),HandleBattlePointsChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UpgradeBuildingResponse),HandleUpgradeBuildingResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(FortifyBuildingResponse),HandleFortifyBuildingResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RecycleBuildingResponse),HandleRecycleBuildingResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(CancelConstructionResponse),HandleCancelConstructionResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ActivateBuildingResponse),HandleActivateBuildingResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(MoveBuildingResponse),HandleMoveBuildingResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingLevelUpgradeJobFinishedEventNotification),HandleBuildingLevelUpgradeJobFinishedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingLevelUpgradeJobScheduledEventNotification),HandleBuildingLevelUpgradeJobScheduledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingFortificationJobFinishedEventNotification),HandleBuildingFortificationJobFinishedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingFortificationJobScheduledNotification),HandleBuildingFortificationJobScheduledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingConstructionCancelledEventNotification),HandleBuildingConstructionCancelledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UserStatusResponse),HandleUserStatusResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(InventoryUpdatedEventNotification),HandleInventoryUpdatedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingActivatedEventNotification),HandleBuildingActivatedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingRecycledEventNotification),HandleBuildingRecycledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(CityBuildingMovedEventNotification),HandleCityBuildingMovedEventNotification,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(WorldChatMessageReceivedEventNotification),HandleWorldChatMessageReceivedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(AllianceChatMessageReceivedEventNotification),HandleAllianceChatMessageReceivedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UserBannedEventNotification),HandleUserBannedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ShowCaptchaEventNotification),HandleShowCaptchaEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ConfirmCaptchaResponse),HandleConfirmCaptchaResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuyDecorationResponse),HandleBuyDecorationResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RaceStatusChangedEventNotification),HandleRaceStatusChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SetAvatarResponse),HandleSetAvatarResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TournamentEndedEventNotification),HandleTournamentEndedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TournamentAttackRemainingDurChangedEventNotification),HandleTournamentAttackRemainingDurChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TournamentStatusChangedEventNotification),HandleTournamentStatusChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TrainUnitResponse),HandleTrainUnitResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RecruitUnitResponse),HandleRecruitUnitResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(StartRepairsResponse),HandleStartRepairsResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RecruitUnitJobScheduledEventNotification),HandleRecruitUnitJobScheduledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitRecruitedEventNotification),HandleUnitRecruitedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TrainUnitJobScheduledEventNotification),HandleTrainUnitJobScheduledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(HireUnitResponse),HandleHireUnitResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitHiredEventNotification),HandleUnitHiredEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitsExecutedEventNotification),HandleUnitsExecutedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitLevelIncreasedEventNotification),HandleUnitLevelIncreasedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingDamagedEventNotification),HandleBuildingDamagedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingRepairJobFinishedEventNotification),HandleBuildingRepairJobFinishedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingRepairJobScheduledEventNotification),HandleBuildingRepairJobScheduledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuyItemResponse),HandleBuyItemResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(HelpFriendResponse),HandleHelpFriendResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(VisitCityEndedEventNotification),HandleVisitCityEndedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(CityHelpedEventNotification),HandleCityHelpedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ClaimQuestResponse),HandleClaimQuestResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(VisibleQuestsChangedNotification),HandleVisibleQuestsChangedNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ItemInventoryChangedEventNotification),HandleItemInventoryChangedEventNotification,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(CityDimensionsUpdatedEventNotification),HandleCityDimensionsUpdatedEventNotification,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(NumberOfWorkersChangedEventNotification),HandleNumberOfWorkersChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitsDeployedToWatchPostEventNotification),HandleUnitsDeployedToWatchPostEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitsKilledInWatchPostEventNotification),HandleUnitsKilledInWatchPostEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RecruitmentCancelledEventNotification),HandleRecruitmentCancelledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(HiringInfoChangedEventNotification),HandleHiringInfoChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetHiringStatusResponse),HandleGetHiringStatusResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(QueuedHiringsCancelledEventNotification),HandleQueuedHiringsCancelledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ServerSpeedChangedEventNotification),HandleServerSpeedChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ApplyCityPlanResponse),HandleApplyCityPlanResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SaveCityPlanResponse),HandleSaveCityPlanResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SetCityPlanSlotsResponse),HandleSetCityPlanSlotsResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(LoadCityPlanResponse),HandleLoadCityPlanResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetCityPlansResponse),HandleGetCityPlansResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetMapInfoResponse),HandleGetMapInfoResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(CaptureBeastResponse),HandleCaptureBeastResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BeastStatusChangedEventNotification),HandleBeastStatusChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(EvolveBeastResponse),HandleEvolveBeastResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TrainBeastResponse),HandleTrainBeastResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(HealBeastResponse),HandleHealBeastResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ThawBeastResponse),HandleThawBeastResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(FreezeBeastResponse),HandleFreezeBeastResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitsKilledForBeastEventNotification),HandleUnitsKilledForBeastEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BeastUnlockedEventNotification),HandleBeastUnlockedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingStaffAssignedEventNotification),HandleBuildingStaffAssignedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(WorkerStaffAssignedEventNotification),HandleWorkerStaffAssignedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(HireStaffResponse),HandleHireStaffResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitTrainingCancelledEventNotification),HandleUnitTrainingCancelledEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(AllBuildingsRepairedEventNotification),HandleAllBuildingsRepairedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ResourcesHarvestedEventNotification),HandleResourcesHarvestedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnitRewardsAddedEventNotification),HandleUnitRewardsAddedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UpdatePigeonPostSubscriptionsMessageResponse),HandleUpdatePigeonPostSubscriptionsMessageResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SubscribedActionsUpdatedEventNotification),HandleSubscribedActionsUpdatedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BankGoldResponse),HandleBankGoldResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GoldBankedEventNotification),HandleGoldBankedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GoldTimerUpdatedEventNotification),HandleGoldTimerUpdatedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SessionClosedNotification),HandleSessionClosedNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetRankingPageResponse),HandleGetRankingPageResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetAttackLogsResponse),HandleGetAttackLogsResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetBattleReportResponse),HandleGetBattleReportResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(EndAttackResponse),HandleEndAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(StartSpyingResponse),HandleStartSpyingResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SpyTimeoutEventNotification),HandleSpyTimeoutEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(FriendWatchpostHelpNotification),HandleFriendWatchpostHelpNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(PrepareNPCAttackResponse),HandlePrepareNPCAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(NPCAttackTimeUpdatedEventNotification),HandleNPCAttackTimeUpdatedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(DelayNPCAttackResponse),HandleDelayNPCAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(StartNPCAttackResponse),HandleStartNPCAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(StartTuskHornAttackResponse),HandleStartTuskHornAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ExtendBattleDurationResponse),HandleExtendAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UpdateUserTutorialResponse),HandleUpdateUserTutorialResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(DailyPerUserHelpCapacityReachedEventNotification),HandleDailyPerUserHelpCapacityReachedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ReadAttackLogResponse),HandleReadAttackLogResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(MaintenanceNotification),HandleMaintenanceNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GoldGiftReceivedEventNotification),HandleGoldGiftReceivedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetAlliancesPageResponse),HandleGetAlliancesPageResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SearchAllianceResponse),HandleSearchAllianceResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(CreateAllianceResponse),HandleCreateAllianceResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(EditAllianceResponse),HandleEditAllianceResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(QuitAllianceResponse),HandleQuitAllianceResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetAllianceInfoResponse),HandleGetAllianceInfoResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetAllianceMembersResponse),HandleGetAllianceMembersResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetAllianceMemberContributionsResponse),HandleGetAllianceMemberContributionsResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetAllianceCandidatesResponse),HandleGetAllianceCandidatesResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SearchAllianceCandidateResponse),HandleSearchAllianceCandidateResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(JoinAllianceResponse),HandleJoinAllianceResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(InviteToAllianceResponse),HandleInviteToAllianceResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(CancelAllianceInvitationResponse),HandleCancelAllianceInvitationResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(KickAllianceMemberResponse),HandleKickAllianceMemberResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ReplyToAllianceInvitationResponse),HandleReplyToAllianceInvitationResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ReplyToJoinAllianceRequestResponse),HandleReplyToJoinAllianceRequestResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(AllianceStatusChangedNotification),HandleAllianceStatusChangedNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UserIsInvitedToAllianceNotification),HandleUserIsInvitedToAllianceNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RemoveRejectedAllianceInvitationResponse),HandleRemoveRejectedAllianceInvitationResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetRequestedAlliancesResponse),HandleGetRequestedAlliancesResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(ReplyToAllianceInvitationNotification),HandleReplyToAllianceInvitationNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetTournamentsPageResponse),HandleGetTournamentsPageResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UseEventItemResponse),HandleUseEventItemReponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetLeagueMembersResponse),HandleGetLeagueMembersResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UserIsPlacedIntoALeagueNotification),HandleUserIsPlacedIntoALeagueNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SeasonEndedNotification),HandleSeasonEndedNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UserIsRemovedFromLeagueNotification),HandleUserIsRemovedFromLeagueNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RearmTrapsResponse),HandleRearmTrapsResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(SkipNPCAttackResponse),HandleSkipNPCAttackResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BuildingHelpedNotification),HandleBuildingHelpedNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetUnitsOfAllianceMemberResponse),HandleGetUnitsOfAllianceMemberResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TransferUnitsToAllianceMemberResponse),HandleTransferUnitsToAllianceMemberResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(AllianceUnitsReceivedEventNotification),HandleAllianceUnitsReceivedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(RechargeCatapultResponse),HandleRechargeCatapultResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(UnlockEventItemResponse),HandleUnlockEventItemResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetWatchPostUnitsOfFriendResponse),HandleGetWatchPostUnitsOfFriendResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TransferWatchPostUnitsToFriendResponse),HandleTransferWatchPostUnitsToFriendResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(EventItemQueueChangedEventNotification),HandleEventItemQueueChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(TavernSpinResponse),HandleTavernSpinResponseCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(BeastCannonAmmoAmountChanedEventNotification),HandleBeastCannonAmmoAmountChangedEventNotificationCommand,MessageReceivedEvent);
         commandMap.mapEvent(_loc1_.getEventTypeFor(GetUserIdsOfFriendsResp),HandleGetUserIdsOfFriendsRespCommand,MessageReceivedEvent);
      }
   }
}

