package wom.controller.command.bootstrap
{
   import peak.messaging.DefaultOutgoingMessageMap;
   import peak.messaging.IncomingMessageMap;
   import peak.messaging.OutgoingMessageMap;
   import wom.controller.PCommand;
   import wom.controller.command.WomIncomingMessageMap;
   import wom.model.game.attack.GameModeType;
   import wom.model.message.notification.AllBuildingsRepairedEventNotification;
   import wom.model.message.notification.AllianceChatMessageReceivedEventNotification;
   import wom.model.message.notification.BattlePointsChangedEventNotification;
   import wom.model.message.notification.BeastCannonAmmoAmountChanedEventNotification;
   import wom.model.message.notification.BeastStatusChangedEventNotification;
   import wom.model.message.notification.BeastUnlockedEventNotification;
   import wom.model.message.notification.BuildingActivatedEventNotification;
   import wom.model.message.notification.BuildingConstructionCancelledEventNotification;
   import wom.model.message.notification.BuildingDamagedEventNotification;
   import wom.model.message.notification.BuildingFortificationJobFinishedEventNotification;
   import wom.model.message.notification.BuildingFortificationJobScheduledNotification;
   import wom.model.message.notification.BuildingHelpedNotification;
   import wom.model.message.notification.BuildingLevelUpgradeJobFinishedEventNotification;
   import wom.model.message.notification.BuildingLevelUpgradeJobScheduledEventNotification;
   import wom.model.message.notification.BuildingRecycledEventNotification;
   import wom.model.message.notification.BuildingRepairJobFinishedEventNotification;
   import wom.model.message.notification.BuildingRepairJobScheduledEventNotification;
   import wom.model.message.notification.BuildingStaffAssignedEventNotification;
   import wom.model.message.notification.CityBuildingMovedEventNotification;
   import wom.model.message.notification.CityDimensionsUpdatedEventNotification;
   import wom.model.message.notification.CityHelpedEventNotification;
   import wom.model.message.notification.DailyPerUserHelpCapacityReachedEventNotification;
   import wom.model.message.notification.EventItemQueueChangedEventNotification;
   import wom.model.message.notification.EventPointsChangedEventNotification;
   import wom.model.message.notification.ExperiencePointsChangedEventNotification;
   import wom.model.message.notification.FriendWatchpostHelpNotification;
   import wom.model.message.notification.GetHiringStatusResponse;
   import wom.model.message.notification.GoldAmountChangedEventNotification;
   import wom.model.message.notification.GoldBankedEventNotification;
   import wom.model.message.notification.GoldGiftReceivedEventNotification;
   import wom.model.message.notification.GoldTimerUpdatedEventNotification;
   import wom.model.message.notification.HiringInfoChangedEventNotification;
   import wom.model.message.notification.InventoryUpdatedEventNotification;
   import wom.model.message.notification.ItemInventoryChangedEventNotification;
   import wom.model.message.notification.MaintenanceNotification;
   import wom.model.message.notification.NPCAttackTimeUpdatedEventNotification;
   import wom.model.message.notification.NumberOfWorkersChangedEventNotification;
   import wom.model.message.notification.QueuedHiringsCancelledEventNotification;
   import wom.model.message.notification.RaceStatusChangedEventNotification;
   import wom.model.message.notification.ReconPointsChangedEventNotification;
   import wom.model.message.notification.RecruitUnitJobScheduledEventNotification;
   import wom.model.message.notification.RecruitmentCancelledEventNotification;
   import wom.model.message.notification.ResourceCapacityUpdatedEventNotification;
   import wom.model.message.notification.ResourcesChangedEventNotification;
   import wom.model.message.notification.ResourcesHarvestedEventNotification;
   import wom.model.message.notification.ServerSpeedChangedEventNotification;
   import wom.model.message.notification.SessionClosedNotification;
   import wom.model.message.notification.ShowCaptchaEventNotification;
   import wom.model.message.notification.SpyTimeoutEventNotification;
   import wom.model.message.notification.StatusNotification;
   import wom.model.message.notification.SubscribedActionsUpdatedEventNotification;
   import wom.model.message.notification.TournamentAttackRemainingDurChangedEventNotification;
   import wom.model.message.notification.TournamentEndedEventNotification;
   import wom.model.message.notification.TournamentStatusChangedEventNotification;
   import wom.model.message.notification.TrainUnitJobScheduledEventNotification;
   import wom.model.message.notification.UnitHiredEventNotification;
   import wom.model.message.notification.UnitLevelIncreasedEventNotification;
   import wom.model.message.notification.UnitRecruitedEventNotification;
   import wom.model.message.notification.UnitRewardsAddedEventNotification;
   import wom.model.message.notification.UnitTrainingCancelledEventNotification;
   import wom.model.message.notification.UnitsDeployedToWatchPostEventNotification;
   import wom.model.message.notification.UnitsExecutedEventNotification;
   import wom.model.message.notification.UnitsKilledForBeastEventNotification;
   import wom.model.message.notification.UnitsKilledInWatchPostEventNotification;
   import wom.model.message.notification.UserBannedEventNotification;
   import wom.model.message.notification.VisibleQuestsChangedNotification;
   import wom.model.message.notification.VisitCityEndedEventNotification;
   import wom.model.message.notification.WorkerStaffAssignedEventNotification;
   import wom.model.message.notification.WorldChatMessageReceivedEventNotification;
   import wom.model.message.notification.alliance.AllianceStatusChangedNotification;
   import wom.model.message.notification.alliance.AllianceUnitsReceivedEventNotification;
   import wom.model.message.notification.alliance.ReplyToAllianceInvitationNotification;
   import wom.model.message.notification.alliance.UserIsInvitedToAllianceNotification;
   import wom.model.message.notification.league.SeasonEndedNotification;
   import wom.model.message.notification.league.UserIsPlacedIntoALeagueNotification;
   import wom.model.message.notification.league.UserIsRemovedFromLeagueNotification;
   import wom.model.message.request.ActivateBuildingRequest;
   import wom.model.message.request.AddWaypointsRequest;
   import wom.model.message.request.ApplyCityPlanRequest;
   import wom.model.message.request.AuthRequest;
   import wom.model.message.request.BankAllResourcesRequest;
   import wom.model.message.request.BankGoldRequest;
   import wom.model.message.request.BankResourcesRequest;
   import wom.model.message.request.BeastDeployedRequest;
   import wom.model.message.request.BuildEventItemRequest;
   import wom.model.message.request.BuyDecorationRequest;
   import wom.model.message.request.BuyItemRequest;
   import wom.model.message.request.BuyPartRequest;
   import wom.model.message.request.BuyUnitRequest;
   import wom.model.message.request.CancelActiveHiringRequest;
   import wom.model.message.request.CancelConstructionRequest;
   import wom.model.message.request.CancelEventItemBuildRequest;
   import wom.model.message.request.CancelRecruitmentRequest;
   import wom.model.message.request.CancelUnitTrainingRequest;
   import wom.model.message.request.CaptureBeastRequest;
   import wom.model.message.request.CatapultUsedRequest;
   import wom.model.message.request.ChatAnomalyDetectionRequest;
   import wom.model.message.request.ChatAuthRequest;
   import wom.model.message.request.ClaimQuestRequest;
   import wom.model.message.request.ConfirmCaptchaRequest;
   import wom.model.message.request.ConstructBuildingRequest;
   import wom.model.message.request.DelayNPCAttackRequest;
   import wom.model.message.request.DeployUnitsToWatchPostRequest;
   import wom.model.message.request.EndAttackRequest;
   import wom.model.message.request.EndNPCAttackRequest;
   import wom.model.message.request.EndTuskHornAttackRequest;
   import wom.model.message.request.EndVisitingCityRequest;
   import wom.model.message.request.EvolveBeastRequest;
   import wom.model.message.request.ExecuteUnitRequest;
   import wom.model.message.request.ExtendBattleDurationRequest;
   import wom.model.message.request.FinishAllHiresRequest;
   import wom.model.message.request.FinishEventItemBuildRequest;
   import wom.model.message.request.FortifyBuildingRequest;
   import wom.model.message.request.ForwardNPCAttackRequest;
   import wom.model.message.request.FreezeBeastRequest;
   import wom.model.message.request.GetAttackLogsRequest;
   import wom.model.message.request.GetBattleReportRequest;
   import wom.model.message.request.GetCityPlansRequest;
   import wom.model.message.request.GetHiringStatusRequest;
   import wom.model.message.request.GetMapInfoRequest;
   import wom.model.message.request.GetNewCaptchaRequest;
   import wom.model.message.request.GetRankingPageRequest;
   import wom.model.message.request.GetUserIdsOfFriendsRequest;
   import wom.model.message.request.GetVisibleQuestsRequest;
   import wom.model.message.request.GetWatchPostUnitsOfFriendRequest;
   import wom.model.message.request.HealBeastRequest;
   import wom.model.message.request.HelpFriendRequest;
   import wom.model.message.request.HireStaffRequest;
   import wom.model.message.request.HireUnitRequest;
   import wom.model.message.request.HireWorkerRequest;
   import wom.model.message.request.IdleWorkerRequest;
   import wom.model.message.request.KillUnitsInWatchPost;
   import wom.model.message.request.LoadCityPlanRequest;
   import wom.model.message.request.MobileApplicationStatusChangedRequest;
   import wom.model.message.request.MoveBuildingRequest;
   import wom.model.message.request.PrepareNPCAttackRequest;
   import wom.model.message.request.ProgressTutorialStepRequest;
   import wom.model.message.request.ReadAttackLogRequest;
   import wom.model.message.request.RearmTrapsRequest;
   import wom.model.message.request.RechargeBeastCannonRequest;
   import wom.model.message.request.RechargeCatapultRequest;
   import wom.model.message.request.RecruitUnitRequest;
   import wom.model.message.request.RecycleBuildingRequest;
   import wom.model.message.request.RemoveDeployedUnitsRequest;
   import wom.model.message.request.RemoveQueuedHiresRequest;
   import wom.model.message.request.SaveCityPlanRequest;
   import wom.model.message.request.SaveDeltaTimeRequest;
   import wom.model.message.request.SellPartRequest;
   import wom.model.message.request.SendAllianceChatMessageRequest;
   import wom.model.message.request.SendWorldChatMessageRequest;
   import wom.model.message.request.SetAttackerNPCUnitsRequest;
   import wom.model.message.request.SetAvatarRequest;
   import wom.model.message.request.SetCityPlanSlotsRequest;
   import wom.model.message.request.SetMandatoryTutorialCompletedRequest;
   import wom.model.message.request.SkipAllQuestTasksRequest;
   import wom.model.message.request.SkipNPCAttackRequest;
   import wom.model.message.request.SkipQuestTaskRequest;
   import wom.model.message.request.StartAttackRequest;
   import wom.model.message.request.StartNPCAttackRequest;
   import wom.model.message.request.StartQuickAttackRequest;
   import wom.model.message.request.StartRepairsRequest;
   import wom.model.message.request.StartSpyingRequest;
   import wom.model.message.request.StartTuskHornAttackRequest;
   import wom.model.message.request.StartVisitingCityRequest;
   import wom.model.message.request.StartVisitingNPCCityRequest;
   import wom.model.message.request.StatusRequest;
   import wom.model.message.request.ThawBeastRequest;
   import wom.model.message.request.TrainBeastRequest;
   import wom.model.message.request.TrainUnitRequest;
   import wom.model.message.request.TransferUnitsToFriendWatchPostRequest;
   import wom.model.message.request.UnlockEventItemRequest;
   import wom.model.message.request.UpdateNPCAttackChoiceRequest;
   import wom.model.message.request.UpdatePigeonPostSubscriptionsMessageRequest;
   import wom.model.message.request.UpdateTutorialRequest;
   import wom.model.message.request.UpgradeBuildingRequest;
   import wom.model.message.request.UseEventItemRequest;
   import wom.model.message.request.UseResourceGiftRequest;
   import wom.model.message.request.UseUnitGiftRequest;
   import wom.model.message.request.UserStatusRequest;
   import wom.model.message.request.alliance.CancelAllianceInvitationRequest;
   import wom.model.message.request.alliance.CreateAllianceRequest;
   import wom.model.message.request.alliance.EditAllianceRequest;
   import wom.model.message.request.alliance.GetAllianceCandidatesRequest;
   import wom.model.message.request.alliance.GetAllianceInfoRequest;
   import wom.model.message.request.alliance.GetAllianceMemberConstributionsRequest;
   import wom.model.message.request.alliance.GetAllianceMembersRequest;
   import wom.model.message.request.alliance.GetAlliancesPageRequest;
   import wom.model.message.request.alliance.GetRequestedAlliancesRequest;
   import wom.model.message.request.alliance.GetTournamentsPageRequest;
   import wom.model.message.request.alliance.GetUnitsOfAllianceMemberRequest;
   import wom.model.message.request.alliance.InviteToAllianceRequest;
   import wom.model.message.request.alliance.JoinAllianceRequest;
   import wom.model.message.request.alliance.KickAllianceMemberRequest;
   import wom.model.message.request.alliance.LeaveAllianceRequest;
   import wom.model.message.request.alliance.QuitAllianceRequest;
   import wom.model.message.request.alliance.RemoveRejectedAllianceInvitationRequest;
   import wom.model.message.request.alliance.ReplyToAllianceInvitationRequest;
   import wom.model.message.request.alliance.ReplyToAllianceJoinRequestRequest;
   import wom.model.message.request.alliance.SearchAllianceCandidateRequest;
   import wom.model.message.request.alliance.SearchAllianceRequest;
   import wom.model.message.request.alliance.TournamentAttackRequest;
   import wom.model.message.request.alliance.TransferUnitsToAllianceMemberRequest;
   import wom.model.message.request.league.GetLeagueMembersRequest;
   import wom.model.message.request.tavern.TavernSpinRequest;
   import wom.model.message.response.AcceptStaffRequestResponse;
   import wom.model.message.response.ActivateBuildingResponse;
   import wom.model.message.response.ApplyCityPlanResponse;
   import wom.model.message.response.AuthResponse;
   import wom.model.message.response.BankAllResourcesResponse;
   import wom.model.message.response.BankGoldResponse;
   import wom.model.message.response.BankResourcesResponse;
   import wom.model.message.response.BuildEventItemResponse;
   import wom.model.message.response.BuyDecorationResponse;
   import wom.model.message.response.BuyItemResponse;
   import wom.model.message.response.CancelConstructionResponse;
   import wom.model.message.response.CancelEventItemBuildResponse;
   import wom.model.message.response.CaptureBeastResponse;
   import wom.model.message.response.ChatAuthResponse;
   import wom.model.message.response.ClaimQuestResponse;
   import wom.model.message.response.ConfirmCaptchaResponse;
   import wom.model.message.response.ConstructBuildingResponse;
   import wom.model.message.response.DefaultResponse;
   import wom.model.message.response.DelayNPCAttackResponse;
   import wom.model.message.response.EndAttackResponse;
   import wom.model.message.response.EndNPCAttackResponse;
   import wom.model.message.response.EvolveBeastResponse;
   import wom.model.message.response.ExtendBattleDurationResponse;
   import wom.model.message.response.FinishEventItemBuildResponse;
   import wom.model.message.response.FortifyBuildingResponse;
   import wom.model.message.response.FreezeBeastResponse;
   import wom.model.message.response.GetAttackLogsResponse;
   import wom.model.message.response.GetBattleReportResponse;
   import wom.model.message.response.GetCityPlansResponse;
   import wom.model.message.response.GetMapInfoResponse;
   import wom.model.message.response.GetRankingPageResponse;
   import wom.model.message.response.GetUserIdsOfFriendsResp;
   import wom.model.message.response.GetWatchPostUnitsOfFriendResponse;
   import wom.model.message.response.HealBeastResponse;
   import wom.model.message.response.HelpFriendResponse;
   import wom.model.message.response.HireStaffResponse;
   import wom.model.message.response.HireUnitResponse;
   import wom.model.message.response.LoadCityPlanResponse;
   import wom.model.message.response.MoveBuildingResponse;
   import wom.model.message.response.PrepareNPCAttackResponse;
   import wom.model.message.response.ProgressTutorialStepResponse;
   import wom.model.message.response.ReadAttackLogResponse;
   import wom.model.message.response.RearmTrapsResponse;
   import wom.model.message.response.RechargeBeastCannonResponse;
   import wom.model.message.response.RechargeCatapultResponse;
   import wom.model.message.response.RecruitUnitResponse;
   import wom.model.message.response.RecycleBuildingResponse;
   import wom.model.message.response.SaveCityPlanResponse;
   import wom.model.message.response.SetCityPlanSlotsResponse;
   import wom.model.message.response.SkipNPCAttackResponse;
   import wom.model.message.response.StartAttackResponse;
   import wom.model.message.response.StartNPCAttackResponse;
   import wom.model.message.response.StartRepairsResponse;
   import wom.model.message.response.StartSpyingResponse;
   import wom.model.message.response.StartTuskHornAttackResponse;
   import wom.model.message.response.StartVisitingCityResponse;
   import wom.model.message.response.ThawBeastResponse;
   import wom.model.message.response.TrainBeastResponse;
   import wom.model.message.response.TrainUnitResponse;
   import wom.model.message.response.TransferWatchPostUnitsToFriendResponse;
   import wom.model.message.response.UnlockEventItemResponse;
   import wom.model.message.response.UpdatePigeonPostSubscriptionsMessageResponse;
   import wom.model.message.response.UpdateUserTutorialResponse;
   import wom.model.message.response.UpgradeBuildingResponse;
   import wom.model.message.response.UseEventItemResponse;
   import wom.model.message.response.UseResourceGiftResponse;
   import wom.model.message.response.UseUnitGiftResponse;
   import wom.model.message.response.UserStatusResponse;
   import wom.model.message.response.alliance.CancelAllianceInvitationResponse;
   import wom.model.message.response.alliance.CreateAllianceResponse;
   import wom.model.message.response.alliance.EditAllianceResponse;
   import wom.model.message.response.alliance.GetAllianceCandidatesResponse;
   import wom.model.message.response.alliance.GetAllianceInfoResponse;
   import wom.model.message.response.alliance.GetAllianceMemberContributionsResponse;
   import wom.model.message.response.alliance.GetAllianceMembersResponse;
   import wom.model.message.response.alliance.GetAlliancesPageResponse;
   import wom.model.message.response.alliance.GetRequestedAlliancesResponse;
   import wom.model.message.response.alliance.GetTournamentsPageResponse;
   import wom.model.message.response.alliance.GetUnitsOfAllianceMemberResponse;
   import wom.model.message.response.alliance.InviteToAllianceResponse;
   import wom.model.message.response.alliance.JoinAllianceResponse;
   import wom.model.message.response.alliance.KickAllianceMemberResponse;
   import wom.model.message.response.alliance.QuitAllianceResponse;
   import wom.model.message.response.alliance.RemoveRejectedAllianceInvitationResponse;
   import wom.model.message.response.alliance.ReplyToAllianceInvitationResponse;
   import wom.model.message.response.alliance.ReplyToJoinAllianceRequestResponse;
   import wom.model.message.response.alliance.SearchAllianceCandidateResponse;
   import wom.model.message.response.alliance.SearchAllianceResponse;
   import wom.model.message.response.alliance.TransferUnitsToAllianceMemberResponse;
   import wom.model.message.response.guest.SetAvatarResponse;
   import wom.model.message.response.league.GetLeagueMembersResponse;
   import wom.model.message.response.tavern.TavernSpinResponse;
   
   public class BootstrapMessagingCommand extends PCommand
   {
      
      public function BootstrapMessagingCommand()
      {
         super();
      }
      
      override public function execute() : void
      {
         bootstrapIncomingMessageMap();
         bootstrapOutgoingMessageMap();
      }
      
      private function bootstrapIncomingMessageMap() : void
      {
         var _loc1_:WomIncomingMessageMap = new WomIncomingMessageMap();
         _loc1_.mapMessage("authResponse",AuthResponse);
         _loc1_.mapMessage("chatAuthenticateResponse",ChatAuthResponse);
         _loc1_.mapMessage("userStatusResponse",UserStatusResponse);
         _loc1_.mapMessage("constructBuildingResponse",ConstructBuildingResponse);
         _loc1_.mapMessage("buyDecorationResponse",BuyDecorationResponse);
         _loc1_.mapMessage("bankAllResourcesResponse",BankAllResourcesResponse);
         _loc1_.mapMessage("bankResourcesResponse",BankResourcesResponse);
         _loc1_.mapMessage("upgradeBuildingResponse",UpgradeBuildingResponse);
         _loc1_.mapMessage("fortifyBuildingResponse",FortifyBuildingResponse);
         _loc1_.mapMessage("activateBuildingResponse",ActivateBuildingResponse);
         _loc1_.mapMessage("moveBuildingResponse",MoveBuildingResponse);
         _loc1_.mapMessage("recycleBuildingResponse",RecycleBuildingResponse);
         _loc1_.mapMessage("cancelConstructionResponse",CancelConstructionResponse);
         _loc1_.mapMessage("recruitUnitResponse",RecruitUnitResponse);
         _loc1_.mapMessage("trainUnitResponse",TrainUnitResponse);
         _loc1_.mapMessage("startRepairsResponse",StartRepairsResponse);
         _loc1_.mapMessage("buyItemResponse",BuyItemResponse);
         _loc1_.mapMessage("claimQuestResponse",ClaimQuestResponse);
         _loc1_.mapMessage("executeUnitResponse",DefaultResponse);
         _loc1_.mapMessage("deployUnitsToWatchPostResponse",DefaultResponse);
         _loc1_.mapMessage("killUnitsInWatchPostResponse",DefaultResponse);
         _loc1_.mapMessage("hireUnitResponse",HireUnitResponse);
         _loc1_.mapMessage("removeQueuedHiresResponse",DefaultResponse);
         _loc1_.mapMessage("cancelActiveHiringResponse",DefaultResponse);
         _loc1_.mapMessage("buyUnitsResponse",DefaultResponse);
         _loc1_.mapMessage("buyPartResponse",DefaultResponse);
         _loc1_.mapMessage("saveCityPlanResponse",SaveCityPlanResponse);
         _loc1_.mapMessage("setCityPlanSlotsResponse",SetCityPlanSlotsResponse);
         _loc1_.mapMessage("loadCityPlanResponse",LoadCityPlanResponse);
         _loc1_.mapMessage("getCityPlansResponse",GetCityPlansResponse);
         _loc1_.mapMessage("applyCityPlanResponse",ApplyCityPlanResponse);
         _loc1_.mapMessage("startVisitingCityResponse",StartVisitingCityResponse);
         _loc1_.mapMessage("startVisitingNPCCityResponse",StartVisitingCityResponse);
         _loc1_.mapMessage("captureBeastResponse",CaptureBeastResponse);
         _loc1_.mapMessage("evolveBeastResponse",EvolveBeastResponse);
         _loc1_.mapMessage("trainBeastResponse",TrainBeastResponse);
         _loc1_.mapMessage("healBeastResponse",HealBeastResponse);
         _loc1_.mapMessage("thawBeastResponse",ThawBeastResponse);
         _loc1_.mapMessage("freezeBeastResponse",FreezeBeastResponse);
         _loc1_.mapMessage("cancelRecruitmentResponse",DefaultResponse);
         _loc1_.mapMessage("getMapInfoResponse",GetMapInfoResponse);
         _loc1_.mapMessage("hireStaffResponse",HireStaffResponse);
         _loc1_.mapMessage("hireWorkerResponse",DefaultResponse);
         _loc1_.mapMessage("startAttackResponse",StartAttackResponse);
         _loc1_.mapMessage("acceptStaffRequestResponse",AcceptStaffRequestResponse);
         _loc1_.mapMessage("finishAllHiresResponse",DefaultResponse);
         _loc1_.mapMessage("cancelUnitTrainingResponse",DefaultResponse);
         _loc1_.mapMessage("updateNPCAttackChoiceResponse",DefaultResponse);
         _loc1_.mapMessage("sellPartResponse",DefaultResponse);
         _loc1_.mapMessage("useResourceGiftResponse",UseResourceGiftResponse);
         _loc1_.mapMessage("updatePigeonPostSubscriptionsResponse",UpdatePigeonPostSubscriptionsMessageResponse);
         _loc1_.mapMessage("bankGoldResponse",BankGoldResponse);
         _loc1_.mapMessage("getRankingPageResponse",GetRankingPageResponse);
         _loc1_.mapMessage("getAttackLogsResponse",GetAttackLogsResponse);
         _loc1_.mapMessage("getBattleReportResponse",GetBattleReportResponse);
         _loc1_.mapMessage("endAttackResponse",EndAttackResponse);
         _loc1_.mapWomMessage("helpFriendResponse",HelpFriendResponse,[GameModeType.VISIT]);
         _loc1_.mapWomMessage("dailyPerUserHelpCapacityReachedEventNotification",DailyPerUserHelpCapacityReachedEventNotification,[GameModeType.VISIT]);
         _loc1_.mapMessage("updateUserTutorialResponse",UpdateUserTutorialResponse);
         _loc1_.mapMessage("endNPCAttackResponse",EndNPCAttackResponse);
         _loc1_.mapMessage("startNPCAttackResponse",StartNPCAttackResponse);
         _loc1_.mapMessage("startTuskhornAttackResponse",StartTuskHornAttackResponse);
         _loc1_.mapMessage("prepareNPCAttackResponse",PrepareNPCAttackResponse);
         _loc1_.mapMessage("delayNPCAttackResponse",DelayNPCAttackResponse);
         _loc1_.mapMessage("progressTutorialStepResponse",ProgressTutorialStepResponse);
         _loc1_.mapMessage("readAttackLogResponse",ReadAttackLogResponse);
         _loc1_.mapMessage("startSpyingResponse",StartSpyingResponse);
         _loc1_.mapMessage("confirmCaptchaResponse",ConfirmCaptchaResponse);
         _loc1_.mapMessage("extendBattleDurationResponse",ExtendBattleDurationResponse);
         _loc1_.mapMessage("getAlliancesPageResponse",GetAlliancesPageResponse);
         _loc1_.mapMessage("getTournamentsPageResponse",GetTournamentsPageResponse);
         _loc1_.mapMessage("searchAllianceResponse",SearchAllianceResponse);
         _loc1_.mapMessage("createAllianceResponse",CreateAllianceResponse);
         _loc1_.mapMessage("editAllianceResponse",EditAllianceResponse);
         _loc1_.mapMessage("leaveAllianceResponse",QuitAllianceResponse);
         _loc1_.mapMessage("getAllianceInfoResponse",GetAllianceInfoResponse);
         _loc1_.mapMessage("getAllianceMembersResponse",GetAllianceMembersResponse);
         _loc1_.mapMessage("getAllianceMemberContributionsResponse",GetAllianceMemberContributionsResponse);
         _loc1_.mapMessage("getAllianceCandidatesResponse",GetAllianceCandidatesResponse);
         _loc1_.mapMessage("searchUserForAllianceResponse",SearchAllianceCandidateResponse);
         _loc1_.mapMessage("joinAllianceResponse",JoinAllianceResponse);
         _loc1_.mapMessage("inviteToAllianceResponse",InviteToAllianceResponse);
         _loc1_.mapMessage("cancelAllianceInvitationResponse",CancelAllianceInvitationResponse);
         _loc1_.mapMessage("kickAllianceMemberResponse",KickAllianceMemberResponse);
         _loc1_.mapMessage("replyToAllianceInvitationResponse",ReplyToAllianceInvitationResponse);
         _loc1_.mapMessage("replyToJoinAllianceRequestResponse",ReplyToJoinAllianceRequestResponse);
         _loc1_.mapMessage("removeRejectedAllianceInvitationResponse",RemoveRejectedAllianceInvitationResponse);
         _loc1_.mapMessage("getRequestedAlliancesResponse",GetRequestedAlliancesResponse);
         _loc1_.mapMessage("useEventItemResponse",UseEventItemResponse);
         _loc1_.mapMessage("getLeagueMembersResponse",GetLeagueMembersResponse);
         _loc1_.mapMessage("skipNPCAttackResponse",SkipNPCAttackResponse);
         _loc1_.mapMessage("rearmTrapsResponse",RearmTrapsResponse);
         _loc1_.mapMessage("getUnitsOfAllianceMemberResponse",GetUnitsOfAllianceMemberResponse);
         _loc1_.mapMessage("transferUnitsToAllianceMemberResponse",TransferUnitsToAllianceMemberResponse);
         _loc1_.mapMessage("getWatchPostUnitsOfFriendResponse",GetWatchPostUnitsOfFriendResponse);
         _loc1_.mapMessage("transferUnitsToFriendWatchPostResponse",TransferWatchPostUnitsToFriendResponse);
         _loc1_.mapMessage("rechargeCatapultsResponse",RechargeCatapultResponse);
         _loc1_.mapMessage("unlockEventItemResponse",UnlockEventItemResponse);
         _loc1_.mapMessage("buildEventItemResponse",BuildEventItemResponse);
         _loc1_.mapMessage("cancelEventItemBuildResponse",CancelEventItemBuildResponse);
         _loc1_.mapMessage("finishEventItemBuildResponse",FinishEventItemBuildResponse);
         _loc1_.mapMessage("tavernSpinResponse",TavernSpinResponse);
         _loc1_.mapMessage("useUnitGiftResponse",UseUnitGiftResponse);
         _loc1_.mapMessage("rechargeBeastCannonResponse",RechargeBeastCannonResponse);
         _loc1_.mapMessage("getUserIdsOfFriendsResp",GetUserIdsOfFriendsResp);
         _loc1_.mapMessage("getHiringStatusResponse",GetHiringStatusResponse);
         _loc1_.mapMessage("statusNotification",StatusNotification);
         _loc1_.mapMessage("goldAmountChangedEventNotification",GoldAmountChangedEventNotification);
         _loc1_.mapMessage("reconPointsChangedEventNotification",ReconPointsChangedEventNotification);
         _loc1_.mapMessage("experiencePointsChangedEventNotification",ExperiencePointsChangedEventNotification);
         _loc1_.mapMessage("eventPointsChangedEventNotification",EventPointsChangedEventNotification);
         _loc1_.mapMessage("battlePointsChangedEventNotification",BattlePointsChangedEventNotification);
         _loc1_.mapMessage("inventoryUpdatedEventNotification",InventoryUpdatedEventNotification);
         _loc1_.mapMessage("serverSpeedChangedEventNotification",ServerSpeedChangedEventNotification);
         _loc1_.mapMessage("subscribedActionsUpdatedEventNotification",SubscribedActionsUpdatedEventNotification);
         _loc1_.mapMessage("sessionClosedNotification",SessionClosedNotification);
         _loc1_.mapMessage("npcAttackTimeUpdatedEventNotification",NPCAttackTimeUpdatedEventNotification);
         _loc1_.mapMessage("userBannedEventNotification",UserBannedEventNotification);
         _loc1_.mapMessage("goldGiftReceivedEventNotification",GoldGiftReceivedEventNotification);
         _loc1_.mapMessage("showCaptchaNotification",ShowCaptchaEventNotification);
         _loc1_.mapMessage("allianceStatusChangedNotification",AllianceStatusChangedNotification);
         _loc1_.mapMessage("userIsInvitedToAllianceNotification",UserIsInvitedToAllianceNotification);
         _loc1_.mapMessage("replyToAllianceInvitationNotification",ReplyToAllianceInvitationNotification);
         _loc1_.mapMessage("raceStatusChangedEventNotification",RaceStatusChangedEventNotification);
         _loc1_.mapMessage("userIsPlacedIntoALeagueNotification",UserIsPlacedIntoALeagueNotification);
         _loc1_.mapMessage("seasonEndedNotification",SeasonEndedNotification);
         _loc1_.mapMessage("userIsRemovedFromLeagueNotification",UserIsRemovedFromLeagueNotification);
         _loc1_.mapMessage("setAvatarResponse",SetAvatarResponse);
         _loc1_.mapMessage("tournamentEnded",TournamentEndedEventNotification);
         _loc1_.mapMessage("tourBattleRemDurChangedEventNotification",TournamentAttackRemainingDurChangedEventNotification);
         _loc1_.mapMessage("tournamentStatusChanged",TournamentStatusChangedEventNotification);
         _loc1_.mapWomMessage("eventItemQueueChangedEventNotification",EventItemQueueChangedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("resourcesChangedEventNotification",ResourcesChangedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingHelpedNotification",BuildingHelpedNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("resourceCapacityUpdatedEventNotification",ResourceCapacityUpdatedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingLevelUpgradeJobScheduledEventNotification",BuildingLevelUpgradeJobScheduledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingLevelUpgradeJobFinishedEventNotification",BuildingLevelUpgradeJobFinishedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingFortificationJobScheduledEventNotification",BuildingFortificationJobScheduledNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingFortificationJobFinishedEventNotification",BuildingFortificationJobFinishedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingConstructionCancelledEventNotification",BuildingConstructionCancelledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingActivatedEventNotification",BuildingActivatedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("recruitUnitJobScheduledEventNotification",RecruitUnitJobScheduledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitRecruitedEventNotification",UnitRecruitedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("trainUnitJobScheduledEventNotification",TrainUnitJobScheduledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitHiredEventNotification",UnitHiredEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitsExecutedEventNotification",UnitsExecutedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitLevelIncreasedEventNotification",UnitLevelIncreasedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingRecycledEventNotification",BuildingRecycledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingDamagedEventNotification",BuildingDamagedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingRepairJobFinishedEventNotification",BuildingRepairJobFinishedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingRepairJobScheduledEventNotification",BuildingRepairJobScheduledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("visibleQuestsChangedEventNotification",VisibleQuestsChangedNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("cityDimensionsUpdatedEventNotification",CityDimensionsUpdatedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("numberOfWorkersChangedEventNotification",NumberOfWorkersChangedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitsKilledInWatchPostEventNotification",UnitsKilledInWatchPostEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitsKilledInFriendWatchPostEventNotification",UnitsKilledInWatchPostEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitsDeployedToWatchPostEventNotification",UnitsDeployedToWatchPostEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("hiringInfoChangedEventNotification",HiringInfoChangedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("queuedHiringsCancelledEventNotification",QueuedHiringsCancelledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("beastStatusChangedEventNotification",BeastStatusChangedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("recruitmentCancelledEventNotification",RecruitmentCancelledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitsKilledForBeastEventNotification",UnitsKilledForBeastEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("buildingStaffAssignedEventNotification",BuildingStaffAssignedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("workerStaffAssignedEventNotification",WorkerStaffAssignedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("cityBuildingMovedEventNotification",CityBuildingMovedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitTrainingCancelledEventNotification",UnitTrainingCancelledEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("allBuildingsRepairedEventNotification",AllBuildingsRepairedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("resourcesHarvestedEventNotification",ResourcesHarvestedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitRewardsAddedEventNotification",UnitRewardsAddedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("visitCityEndedEventNotification",VisitCityEndedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("cityHelpedEventNotification",CityHelpedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("allianceUnitsReceivedEventNotification",AllianceUnitsReceivedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("spyTimeoutEventNotification",SpyTimeoutEventNotification,[GameModeType.VISIT]);
         _loc1_.mapWomMessage("itemInventoryChangedEventNotification",ItemInventoryChangedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("unitsDeployedToFriendWatchPostEventNotification",FriendWatchpostHelpNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("beastUnlockedEventNotification",BeastUnlockedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapWomMessage("beastCannonAmmoAmountChangedEventNotification",BeastCannonAmmoAmountChanedEventNotification,[GameModeType.NORMAL]);
         _loc1_.mapMessage("maintenanceNotif",MaintenanceNotification);
         _loc1_.mapMessage("goldBankedEventNotification",GoldBankedEventNotification);
         _loc1_.mapMessage("goldTimerUpdatedEventNotification",GoldTimerUpdatedEventNotification);
         _loc1_.mapMessage("wChatNotification",WorldChatMessageReceivedEventNotification);
         _loc1_.mapMessage("aChatNotification",AllianceChatMessageReceivedEventNotification);
         injector.mapValue(IncomingMessageMap,_loc1_);
      }
      
      private function bootstrapOutgoingMessageMap() : void
      {
         var _loc1_:OutgoingMessageMap = new DefaultOutgoingMessageMap();
         _loc1_.mapMessage("authenticate",AuthRequest);
         _loc1_.mapMessage("chatAuthenticate",ChatAuthRequest);
         _loc1_.mapMessage("status",StatusRequest);
         _loc1_.mapMessage("userStatus",UserStatusRequest);
         _loc1_.mapMessage("constructBuilding",ConstructBuildingRequest);
         _loc1_.mapMessage("buyDecoration",BuyDecorationRequest);
         _loc1_.mapMessage("bankAllResources",BankAllResourcesRequest);
         _loc1_.mapMessage("bankResources",BankResourcesRequest);
         _loc1_.mapMessage("upgradeBuilding",UpgradeBuildingRequest);
         _loc1_.mapMessage("fortifyBuilding",FortifyBuildingRequest);
         _loc1_.mapMessage("activateBuilding",ActivateBuildingRequest);
         _loc1_.mapMessage("moveBuilding",MoveBuildingRequest);
         _loc1_.mapMessage("recycleBuilding",RecycleBuildingRequest);
         _loc1_.mapMessage("cancelConstruction",CancelConstructionRequest);
         _loc1_.mapMessage("recruitUnit",RecruitUnitRequest);
         _loc1_.mapMessage("trainUnit",TrainUnitRequest);
         _loc1_.mapMessage("startRepairs",StartRepairsRequest);
         _loc1_.mapMessage("buyItem",BuyItemRequest);
         _loc1_.mapMessage("claimQuest",ClaimQuestRequest);
         _loc1_.mapMessage("skipQuestTask",SkipQuestTaskRequest);
         _loc1_.mapMessage("skipAllQuestTasks",SkipAllQuestTasksRequest);
         _loc1_.mapMessage("hireWorker",HireWorkerRequest);
         _loc1_.mapMessage("sellPart",SellPartRequest);
         _loc1_.mapMessage("buyPart",BuyPartRequest);
         _loc1_.mapMessage("executeUnit",ExecuteUnitRequest);
         _loc1_.mapMessage("deployUnitsToWatchPost",DeployUnitsToWatchPostRequest);
         _loc1_.mapMessage("killUnitsInWatchPost",KillUnitsInWatchPost);
         _loc1_.mapMessage("hireUnit",HireUnitRequest);
         _loc1_.mapMessage("removeQueuedHires",RemoveQueuedHiresRequest);
         _loc1_.mapMessage("cancelActiveHiring",CancelActiveHiringRequest);
         _loc1_.mapMessage("cancelRecruitment",CancelRecruitmentRequest);
         _loc1_.mapMessage("saveCityPlan",SaveCityPlanRequest);
         _loc1_.mapMessage("loadCityPlan",LoadCityPlanRequest);
         _loc1_.mapMessage("setCityPlanSlots",SetCityPlanSlotsRequest);
         _loc1_.mapMessage("applyCityPlan",ApplyCityPlanRequest);
         _loc1_.mapMessage("getCityPlans",GetCityPlansRequest);
         _loc1_.mapMessage("startVisitingCity",StartVisitingCityRequest);
         _loc1_.mapMessage("startVisitingNPCCity",StartVisitingNPCCityRequest);
         _loc1_.mapMessage("captureBeast",CaptureBeastRequest);
         _loc1_.mapMessage("evolveBeast",EvolveBeastRequest);
         _loc1_.mapMessage("trainBeast",TrainBeastRequest);
         _loc1_.mapMessage("healBeast",HealBeastRequest);
         _loc1_.mapMessage("thawBeast",ThawBeastRequest);
         _loc1_.mapMessage("freezeBeast",FreezeBeastRequest);
         _loc1_.mapMessage("getMapInfo",GetMapInfoRequest);
         _loc1_.mapMessage("endAttack",EndAttackRequest);
         _loc1_.mapMessage("removeDeployedUnits",RemoveDeployedUnitsRequest);
         _loc1_.mapMessage("beastDeployed",BeastDeployedRequest);
         _loc1_.mapMessage("startAttack",StartAttackRequest);
         _loc1_.mapMessage("hireStaff",HireStaffRequest);
         _loc1_.mapMessage("finishAllHires",FinishAllHiresRequest);
         _loc1_.mapMessage("cancelUnitTraining",CancelUnitTrainingRequest);
         _loc1_.mapMessage("useResourceGift",UseResourceGiftRequest);
         _loc1_.mapMessage("updatePigeonPostSubscriptionsMessage",UpdatePigeonPostSubscriptionsMessageRequest);
         _loc1_.mapMessage("bankGold",BankGoldRequest);
         _loc1_.mapMessage("getRankingPage",GetRankingPageRequest);
         _loc1_.mapMessage("getAttackLogs",GetAttackLogsRequest);
         _loc1_.mapMessage("getBattleReport",GetBattleReportRequest);
         _loc1_.mapMessage("endVisitingCity",EndVisitingCityRequest);
         _loc1_.mapMessage("helpFriend",HelpFriendRequest);
         _loc1_.mapMessage("updateTutorial",UpdateTutorialRequest);
         _loc1_.mapMessage("startNPCAttack",StartNPCAttackRequest);
         _loc1_.mapMessage("startTuskhornAttack",StartTuskHornAttackRequest);
         _loc1_.mapMessage("endNPCAttack",EndNPCAttackRequest);
         _loc1_.mapMessage("endTuskhornAttack",EndTuskHornAttackRequest);
         _loc1_.mapMessage("prepareNPCAttack",PrepareNPCAttackRequest);
         _loc1_.mapMessage("delayNPCAttack",DelayNPCAttackRequest);
         _loc1_.mapMessage("getVisibleQuests",GetVisibleQuestsRequest);
         _loc1_.mapMessage("readAttackLog",ReadAttackLogRequest);
         _loc1_.mapMessage("forwardNPCAttack",ForwardNPCAttackRequest);
         _loc1_.mapMessage("setMandatoryTutorialCompleted",SetMandatoryTutorialCompletedRequest);
         _loc1_.mapMessage("progressTutorialStep",ProgressTutorialStepRequest);
         _loc1_.mapMessage("setAttackerNPCUnits",SetAttackerNPCUnitsRequest);
         _loc1_.mapMessage("updateNPCAttackChoice",UpdateNPCAttackChoiceRequest);
         _loc1_.mapMessage("clientRequest",IdleWorkerRequest);
         _loc1_.mapMessage("worldChat",SendWorldChatMessageRequest);
         _loc1_.mapMessage("allianceChat",SendAllianceChatMessageRequest);
         _loc1_.mapMessage("quickAttack",StartQuickAttackRequest);
         _loc1_.mapMessage("startSpyingCity",StartSpyingRequest);
         _loc1_.mapMessage("getNewCaptcha",GetNewCaptchaRequest);
         _loc1_.mapMessage("confirmCaptcha",ConfirmCaptchaRequest);
         _loc1_.mapMessage("extendBattleDuration",ExtendBattleDurationRequest);
         _loc1_.mapMessage("buyUnits",BuyUnitRequest);
         _loc1_.mapMessage("getAlliancesPage",GetAlliancesPageRequest);
         _loc1_.mapMessage("getTournamentsPage",GetTournamentsPageRequest);
         _loc1_.mapMessage("searchAlliance",SearchAllianceRequest);
         _loc1_.mapMessage("createAlliance",CreateAllianceRequest);
         _loc1_.mapMessage("editAlliance",EditAllianceRequest);
         _loc1_.mapMessage("leaveAlliance",QuitAllianceRequest);
         _loc1_.mapMessage("getAllianceInfo",GetAllianceInfoRequest);
         _loc1_.mapMessage("getAllianceMembers",GetAllianceMembersRequest);
         _loc1_.mapMessage("getAllianceMemberContributions",GetAllianceMemberConstributionsRequest);
         _loc1_.mapMessage("getAllianceCandidates",GetAllianceCandidatesRequest);
         _loc1_.mapMessage("searchUserForAlliance",SearchAllianceCandidateRequest);
         _loc1_.mapMessage("joinAlliance",JoinAllianceRequest);
         _loc1_.mapMessage("inviteToAlliance",InviteToAllianceRequest);
         _loc1_.mapMessage("cancelAllianceInvitation",CancelAllianceInvitationRequest);
         _loc1_.mapMessage("kickAllianceMember",KickAllianceMemberRequest);
         _loc1_.mapMessage("leaveAlliance",LeaveAllianceRequest);
         _loc1_.mapMessage("replyToAllianceInvitation",ReplyToAllianceInvitationRequest);
         _loc1_.mapMessage("replyToAllianceJoinRequest",ReplyToAllianceJoinRequestRequest);
         _loc1_.mapMessage("removeRejectedAllianceInvitation",RemoveRejectedAllianceInvitationRequest);
         _loc1_.mapMessage("getRequestedAlliances",GetRequestedAlliancesRequest);
         _loc1_.mapMessage("useItem",UseEventItemRequest);
         _loc1_.mapMessage("getLeagueMembers",GetLeagueMembersRequest);
         _loc1_.mapMessage("skipNPCAttack",SkipNPCAttackRequest);
         _loc1_.mapMessage("rearmTraps",RearmTrapsRequest);
         _loc1_.mapMessage("addFpsDeltaTime",SaveDeltaTimeRequest);
         _loc1_.mapMessage("addWaypoint",AddWaypointsRequest);
         _loc1_.mapMessage("rechargeCatapults",RechargeCatapultRequest);
         _loc1_.mapMessage("rechargeBeastCannon",RechargeBeastCannonRequest);
         _loc1_.mapMessage("getUnitsOfAllianceMember",GetUnitsOfAllianceMemberRequest);
         _loc1_.mapMessage("transferUnitsToAllianceMember",TransferUnitsToAllianceMemberRequest);
         _loc1_.mapMessage("catapultUsed",CatapultUsedRequest);
         _loc1_.mapMessage("getWatchPostUnitsOfFriend",GetWatchPostUnitsOfFriendRequest);
         _loc1_.mapMessage("transferUnitsToFriendWatchPost",TransferUnitsToFriendWatchPostRequest);
         _loc1_.mapMessage("unlockEventItem",UnlockEventItemRequest);
         _loc1_.mapMessage("buildEventItem",BuildEventItemRequest);
         _loc1_.mapMessage("cancelEventItemBuild",CancelEventItemBuildRequest);
         _loc1_.mapMessage("finishEventItemBuild",FinishEventItemBuildRequest);
         _loc1_.mapMessage("chatAnomalyDetected",ChatAnomalyDetectionRequest);
         _loc1_.mapMessage("tavernSpin",TavernSpinRequest);
         _loc1_.mapMessage("useUnitGift",UseUnitGiftRequest);
         _loc1_.mapMessage("tournamentAttack",TournamentAttackRequest);
         _loc1_.mapMessage("getUserIdsOfFriends",GetUserIdsOfFriendsRequest);
         _loc1_.mapMessage("getHiringStatus",GetHiringStatusRequest);
         _loc1_.mapMessage("mobileApplicationStatusChanged",MobileApplicationStatusChangedRequest);
         _loc1_.mapMessage("setAvatar",SetAvatarRequest);
         injector.mapValue(OutgoingMessageMap,_loc1_);
      }
   }
}

